DROP SCHEMA IF EXISTS EXASOL_CT_NULLABLE CASCADE;

CREATE SCHEMA EXASOL_CT_NULLABLE;

OPEN SCHEMA EXASOL_CT_NULLABLE;

CREATE TABLE READ_NULLABLE (
    C_VARCHAR_NULLABLE VARCHAR(20) NULL,
    C_VARCHAR_NOT_NULLABLE VARCHAR(20) NOT NULL
);

CREATE TABLE WRITE_NULLABLE LIKE READ_NULLABLE;

INSERT INTO READ_NULLABLE VALUES(NULL, 'Not Nullable');
INSERT INTO READ_NULLABLE VALUES('foo', 'bar');